### ISSUE TITLE
完善 API 文檔

### ISSUE THREAD

**Issue by ken20001207** [chief-noob/Mosoon-Backend#3]
麻煩後端完善 API 文檔以利前端串接，感恩🙏

**Comment by sophheih** [comment]
會依照原本計畫在8號前完成

**Comment by ken20001207** [comment]
完成了以後記得上來 github 把成果丟上來 comment，然後關閉 issue 喔～

**Comment by sophheih** [comment]
mosoon文檔網頁版
[https://chief-noob.postman.co/collections/12194739-69d70d85-e74f-45f9-a6c8-af1655ab830b?version=latest&workspace=4bdf4b9a-ce2a-42e9-8fbf-8f8f90320d7f](url)
