### ISSUE TITLE
希望 API 的 URL 設計可以遵照 REST 原則

### ISSUE THREAD

**Issue by ken20001207** [chief-noob/Mosoon-Backend#6]
剛剛看了一下後端的 URL，發現了這幾點問題：

## 同一個功能，給不同的身分使用，不應該切成兩個 Endpinits：
例如 `/member/update/` 和 `/member/updateAdmin/` 應該合併為一個 Endponit，
或是 `/member/get/` 和 `/member/getAdmin/` 也是相同道理。

透過 Requset 的 Token 判斷請求的人是不是管理員就好了。

## 同一個功能，兩個不同的 Attribute，不應該切成兩個 Endpoints：
例如 `/member/update/` 和 `/member/updatePassword`，
都是更新會員的資料為什麼要分兩個接口呢?

## 不同的 feature 的接口不應該硬塞在一起
例如 `/member/newAddress/`、`/member/updateAddress/`、`/member/delAddress.`、`/member/MemAddress`
他們其實已經是獨立的一個 feat 了，建議拿出來變成 `/address/new` 或是 `/member/address/new` 

## 試著用一個 URL 來代表一個資源，然後不同的 method 代表不同的操作
例如 `/member/<member_id>/` 代表的是一個 `member`
對這個 URL 做 `GET` 就是取得用戶資料
對這個 URL 做 `PUT` 就是更新用戶資料
對這個 URL 做 `DEL` 就是刪除用戶資料

**Comment by ken20001207** [comment]
`/reservation/getThri`、`/reservation/getDate/`、`/reservation/getMem`、`/reservation/all` 
同理，請合併成一個接口，用參數做條件查詢。

**Comment by sophheih** [comment]
我有一個疑問! 就是在更新會員資料跟密碼的部分，大部分程式更新密碼都會獨立出來與更新其他資料分開，多了一部份的驗證性，你覺得要維持著嗎

**Comment by ken20001207** [comment]
多了驗證性並不是因為他把更新密碼的接口獨立出來寫，而是因為獨立出來以後他會要求這個接口除了輸入新密碼還要輸入原本的密碼。這個動作是為了避免有人竊取他人的token以後直接用token去竄改那個被偷的人的密碼，多了一層驗證機制。
如果我們要加入這個驗證機制，那這兩個API勢必要分開寫了（不然我改一般的資料也要重新輸入密碼），但如果我們沒有想要設計的那麼謹慎的話，其實沒有分開的必要和意義。

**Comment by ken20001207** [comment]
這個 issue 拆成各個 feature 的 issue 了
